@host = http://localhost:3000/users


# Register a new user
POST {{host}}/authenticate/register
Content-Type: application/json

{
    "email": "isitconnected@emory.edu",
    "password": "test1234"
}

###
# Login
POST {{host}}/authenticate/login
Content-Type: application/json

{
    "email": "admin@emory.edu",
    "password": "test1234"
}
